=== BugBountyzip/store/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "license": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "author": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": ["name", "email", "url"]
      },
      "repository": {
        "type": "string"
      }
    },
    "required": ["id", "name", "license", "description", "author", "repository"]
  }
}

=== BugBountyzip/store/plugin_packages.json
[
  {
    "id": "autorize",
    "name": "Autorize",
    "license": "MIT",
    "description": "Automated access control testing plugin for Caido",
    "author": {
      "name": "Caido Labs Inc.",
      "email": "dev@caido.io",
      "url": "https://github.com/caido-community/autorize"
    },
    "repository": "caido-community/authorize"
  }
]
